### ISSUE TITLE
Update _config file to exclude vendor directory to enable local running of jekyll for development

### ISSUE THREAD

**Issue by jcohen02** [datacarpentry/openrefine-socialsci#124]
For development purposes, it's really useful to be able to build/run this jekyll site locally to make changes and test them.

At present this doesn't work. The standard approach would be:

Clone the repo and change in to the `openrefine-socialsci` directory then: 

```
bundle install --path vendor/bundle
bundle exec jekyll serve
```

at present, this results in an error when trying to build the site:

```
             Error: could not read file /.../gems/jekyll-3.9.2/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.6.0/gems/jekyll-3.9.2/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.6.0/gems/jekyll-3.9.2/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```

This is a result of the `vendor/bundle` directory not being excluded in the `_config.yml` file. This has been changed in the upstream [Carpentries workshop template config](https://github.com/carpentries/workshop-template/blob/gh-pages/_config.yml), a PR will follow shortly to address this...

**Comment by bencomp** [comment]
Thanks for reporting this and providing #125, @jcohen02! Of course we want to be able to preview changes locally, so we certainly need to resolve this. I can reproduce the error (on macOS with a fresh clone) when I use your commands, but it looks like the issue may have been a lack of documentation. Apologies!

The lessons are based on the [styles repository](https://github.com/carpentries/styles), with an accompanying [example lesson](https://carpentries.github.io/lesson-example/) that explains how to create and update lesson repositories.
If you hadn't seen that, you wouldn't know how to preview the website in the preferred way, which is `make serve`.

We should add these basic instructions to the README (that may link to central documentation, as it should be the same for most lessons – at least until all lessons move to [the new infrastructure](https://carpentries.github.io/workbench/)).
I'll add them after merging #111.

`make serve` is expanded to `bundle config set --local path .vendor/bundle && bundle install && bundle update && bundle exec jekyll`. Using `config set` instead of the `--path` flag may be why I get no errors running `make serve`, because I noticed this when I ran your commands:
```console
$ bundle install --path vendor/bundle
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle'`, and stop using this flag
```

Or maybe it's because of the `.vendor` instead of `vendor`? In my rendered `_site` directory I don't see a `.vendor` directory, even though it's not explicitly excluded. Your PR #125 does update the file to the current template version, because both `vendor` and `.vendor` are indeed excluded in https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/_config.yml (the basis for our `_config.yml`).

But I think the better current solution is to add "Quick start" instructions to the README.
Thanks for your analysis, it was really helpful to determine the underlying causes of the issue.
And hopefully this didn't put you off from contributing… :)

**Comment by jcohen02** [comment]
Thanks very much for the detailed explanation on this @bencomp. I wasn't familiar with the styles repository that you've highlighted that this lesson is based on.

As you suggest, it might be useful to add something into the README about this. However, it's interesting that you didn't experience the same problem with `make serve`. I guess you're right that it's probably the difference between using `.vendor` or `vendor`. I've always used `vendor/bundle` for these things and hadn't seen the use of `.vendor` but I guess that is also a widely used approach given that both are added to the exclude list in the carpentries template `_config.yml`. I was thinking maybe "hidden" directories are ignored by jeykll when scanning for files during a site build, although this would remove the need to add `.vendor` to the exlude list! 🤔  Anyway, this hasn't put me off from contributing 🙂.

**Comment by bencomp** [comment]
I thought the warning about Bundler (not) remembering the vendor path between invocations might have been the issue, but according to <https://jekyllrb.com/docs/structure/>

> Every file or directory beginning with the following characters: ., _ , # or ~ in the source directory will not be included in the destination folder.

I'll work on #126 soon, but first I'll merge the PR.
