### ISSUE TITLE
Typos and organization issues

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/openrefine-socialsci#45]
As part of my checkout process, I had a look at the "OpenRefine for Social Science Data" course (https://datacarpentry.org/openrefine-socialsci/). In the following you find some small comments and suggestions: 
1. Wrong file name in 'Working with OpenRefine'
In the fifth paragraph of 'Creationg a new OpenRefine project', the file name of the example dataset to work with in the course is given: '2. Click "Choose Files" and select the file "SAFI_messy_openrefine.csv"'. 
The file name is not correct. The file to be used is called 'SAFI_openrefine.csv'. 
2. Add a few words about the layout in the 'Working with Open Refine' chapter
So, I am aware that in the instructions on what to contribute and what not to contribute as part of the checkout process, you write that we are not supposed to introduce new concepts etc., as the courses are already quite packed with contents. However, in the chapter 'Working with Open Refine', I find the transition from subchapter on 'Creating a new OpenRefine project' to 'Using Facets' a little abrupt. I think it would be helpful to add a little information about the basic structure of the layout of OR. This would not have to be very extensive and maybe existing content from the Library Carpentry course on OR could be used. In the chapter on 'Layout of OpenRefine, Rows vs Records' (https://librarycarpentry.org/lc-open-refine/03-working-with-data/index.html), there are two subchapters that cover this quite well, in my opinion, and are not very extensive: 'The layout of OpenRefine' and 'Working with data in OpenRefine'. So my suggestion would be to add a small section on 'The layout of OpenRefine' between 'Creating a new OpenRefine project' and 'Using Facets' based on the content of the said two Library Carpentry subchapters/sections. I think this content could be covered in 2-3 minutes of teaching time and would be particularly helpful for participants who don't have any previous experience with OR at. 
3. Typo in "Filtering and Sorting with OpenRefine"
In the exercise in the "Sorting by multiple columns section", there's a typo in 2.: "gps_Lattitude" (instead of "gps_Latitude"). 
4. "unanswered" question in 'Examining numbers in OpenRefine'?
The 'Overview' section of this chapter contains the question 'How can we visualize relationships among columns?', but I don't think that this question is really answered by the current content.

**Comment by saross** [comment]
I have reviewed the recommendations associated with this issue looking for any corrections that still need to be made. As I see it, the current status is:

1. The incorrect filename in 'Working with OpenRefine' has been corrected (see above). 
2. This recommendation is a content issue: should a section be added offering more of a transition from 'Creating a new OpenRefine project' to 'Using Facets'. I agree that a short, 2-3 minute orientation to the OpenRefine UI would be useful, and that information in 'The layout of OpenRefine', 'Working with data in OpenRefine', and 'Rows and Records' (https://librarycarpentry.org/lc-open-refine/03-working-with-data/index.html) would be a good starting point. I have provided a short ad hoc intro like this when I have taught the OpenRefine for Social Science lesson in the past.
3. The GPS_Latitude typo in 'Filtering and Sorting for OpenRefine' has also been fixed (ctrl-f returns nothing for 'Latt').
4. I agree that the question: 'How can we visualize relationships among columns?' does not really fit the content. I will make some suggestions for improvements to this episode as pull requests, focusing on aligning the framing text with the content, rather than the other way around.
