### ISSUE TITLE
What URLs does "Get data from Web Addresses (URLs) not work for?

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/openrefine-socialsci#60]
The [Working with OpenRefine](https://datacarpentry.org/openrefine-socialsci/02-working-with-openrefine/index.html) episode notes:

> Note that at step 1, you could upload data in a standard form from a web address by selecting Get data from Web Addresses (URLs). However, this won’t work for all URLs.

It may be useful to note what kind of  URLs this will not work for.

**Comment by bencomp** [comment]
Rather late, but still: thank you for submitting this issue, @maneesha! I see you opened a similar issue in the OpenRefine for Ecology lesson (datacarpentry/OpenRefine-ecology-lesson#236). That issue was closed because the OpenRefine documentation doesn't provide any more details on this.

I do still think we need to address this. We could replace the sentence "However, this won't work for all URLs" with something like:

> The URLs must point to data in a file type that OpenRefine understands, just like the types that you could upload. Fully understanding this functionality is out of scope for this lesson.

It looks like the URL for the lesson dataset, <https://ndownloader.figshare.com/files/11502815>, is accepted by OpenRefine. We could include that in the section:

> The URLs must point to data in a file type that OpenRefine understands, just like the types that you could upload. Instead of downloading the dataset file as you did in *setup* and uploading it from your computer, you could have submitted its URL here. Fully understanding this functionality is out of scope for this lesson.

How does that sound?
