### ISSUE TITLE
Features now available in Google Sheets outside of OpenRefine

### ISSUE THREAD

**Issue by angela-li** [datacarpentry/openrefine-socialsci#64]
There are a few things covered in this lesson that are now part of Google Sheets: for example, splitting columns, trimming whitespace are now part of the Sheets functionality:

https://support.google.com/docs/answer/6325535?hl=en&ref_topic=9066125

Given that Sheets is becoming more powerful, I wonder if it makes sense to take part of this and lump it into the Spreadsheets lesson...

**Comment by brownsarahm** [comment]
I think it's important to keep these steps in OpenRefine, because OpenRefine is more reproducible than operations that occur in a spreadsheet. Both because it produces the script/log and because it operates on a copy of the data. 

The takeaway from the spreadsheets lesson, at least as I understood it was more about using spreadsheets for data *entry* than data *processing* and as a familiar interface for teaching the concepts of tidy data. I think advocating for data manipulation in spreadsheets is in conflict with our goal to teach best practices. 

However, I don't think it hurts t have multiple ways to do things and compare them, so adding them to spreadsheets could be ok.

**Comment by gtlaflair** [comment]
@brownsarahm I agree with your comments. @angela-li do you think that we can close this issue given Sarah's comments?
